theme: jekyll-theme-midnight
title: "John Gordon"
description: "Professor of Computer Science & Information Systems @<br> <a href='http://www.slcc.edu' target='_blank'>SLCC</a>"
github: "is_project_page: false"
